const mongoose = require('mongoose');
const Customer = require('../models/Customer');

const customers = [
  {
    name: 'Acme Corporation',
    primaryContactFirstName: 'John',
    primaryContactLastName: 'Smith',
    primaryContactEmail: 'john.smith@acme.com',
    primaryContactPhone: '+1-555-0101',
    accountNumber: 'ACC-001',
    website: 'https://acme.com',
    notes: 'Long-term client, prefers email communication',
    billingCurrency: 'USD',
    billingAddress1: '123 Business Park',
    billingAddress2: 'Suite 100',
    billingCountry: 'United States',
    billingState: 'California',
    billingCity: 'San Francisco',
    billingPostal: '94102',
    shippingName: 'Acme Corporation',
    shippingAddress1: '123 Business Park',
    shippingAddress2: 'Suite 100',
    shippingCountry: 'United States',
    shippingState: 'California',
    shippingCity: 'San Francisco',
    shippingPostal: '94102',
    shippingPhone: '+1-555-0101',
    shippingDeliveryInstructions: 'Leave at reception'
  },
  {
    name: 'TechStart Solutions',
    primaryContactFirstName: 'Sarah',
    primaryContactLastName: 'Johnson',
    primaryContactEmail: 'sarah.j@techstart.io',
    primaryContactPhone: '+1-555-0102',
    accountNumber: 'ACC-002',
    website: 'https://techstart.io',
    notes: 'Startup client, net-30 payment terms',
    billingCurrency: 'USD',
    billingAddress1: '456 Innovation Drive',
    billingAddress2: '',
    billingCountry: 'United States',
    billingState: 'Texas',
    billingCity: 'Austin',
    billingPostal: '78701',
    shippingName: 'TechStart Solutions',
    shippingAddress1: '456 Innovation Drive',
    shippingAddress2: '',
    shippingCountry: 'United States',
    shippingState: 'Texas',
    shippingCity: 'Austin',
    shippingPostal: '78701',
    shippingPhone: '+1-555-0102',
    shippingDeliveryInstructions: 'Call upon arrival'
  },
  {
    name: 'Global Retail Inc',
    primaryContactFirstName: 'Michael',
    primaryContactLastName: 'Chen',
    primaryContactEmail: 'm.chen@globalretail.com',
    primaryContactPhone: '+1-555-0103',
    accountNumber: 'ACC-003',
    website: 'https://globalretail.com',
    notes: 'Large volume orders, requires detailed invoices',
    billingCurrency: 'USD',
    billingAddress1: '789 Commerce Blvd',
    billingAddress2: 'Floor 5',
    billingCountry: 'United States',
    billingState: 'New York',
    billingCity: 'New York',
    billingPostal: '10001',
    shippingName: 'Global Retail Inc',
    shippingAddress1: '789 Commerce Blvd',
    shippingAddress2: 'Floor 5',
    shippingCountry: 'United States',
    shippingState: 'New York',
    shippingCity: 'New York',
    shippingPostal: '10001',
    shippingPhone: '+1-555-0103',
    shippingDeliveryInstructions: 'Delivery dock #3'
  },
  {
    name: 'Creative Design Studio',
    primaryContactFirstName: 'Emma',
    primaryContactLastName: 'Williams',
    primaryContactEmail: 'emma@creativestudio.co',
    primaryContactPhone: '+1-555-0104',
    accountNumber: 'ACC-004',
    website: 'https://creativestudio.co',
    notes: 'Creative agency, project-based billing',
    billingCurrency: 'USD',
    billingAddress1: '321 Art District',
    billingAddress2: 'Studio B',
    billingCountry: 'United States',
    billingState: 'Oregon',
    billingCity: 'Portland',
    billingPostal: '97201',
    shippingName: 'Creative Design Studio',
    shippingAddress1: '321 Art District',
    shippingAddress2: 'Studio B',
    shippingCountry: 'United States',
    shippingState: 'Oregon',
    shippingCity: 'Portland',
    shippingPostal: '97201',
    shippingPhone: '+1-555-0104',
    shippingDeliveryInstructions: 'Ring doorbell twice'
  },
  {
    name: 'Mountain View Logistics',
    primaryContactFirstName: 'David',
    primaryContactLastName: 'Brown',
    primaryContactEmail: 'd.brown@mountainviewlogistics.com',
    primaryContactPhone: '+1-555-0105',
    accountNumber: 'ACC-005',
    website: 'https://mountainviewlogistics.com',
    notes: 'Shipping and logistics company',
    billingCurrency: 'USD',
    billingAddress1: '555 Warehouse Way',
    billingAddress2: '',
    billingCountry: 'United States',
    billingState: 'Colorado',
    billingCity: 'Denver',
    billingPostal: '80202',
    shippingName: 'Mountain View Logistics',
    shippingAddress1: '555 Warehouse Way',
    shippingAddress2: '',
    shippingCountry: 'United States',
    shippingState: 'Colorado',
    shippingCity: 'Denver',
    shippingPostal: '80202',
    shippingPhone: '+1-555-0105',
    shippingDeliveryInstructions: 'Use loading bay A'
  },
  {
    name: 'Sunrise Healthcare',
    primaryContactFirstName: 'Lisa',
    primaryContactLastName: 'Anderson',
    primaryContactEmail: 'lisa.anderson@sunrisehealth.com',
    primaryContactPhone: '+1-555-0106',
    accountNumber: 'ACC-006',
    website: 'https://sunrisehealth.com',
    notes: 'Healthcare provider, strict compliance requirements',
    billingCurrency: 'USD',
    billingAddress1: '888 Medical Center',
    billingAddress2: 'Building 2',
    billingCountry: 'United States',
    billingState: 'Florida',
    billingCity: 'Miami',
    billingPostal: '33101',
    shippingName: 'Sunrise Healthcare',
    shippingAddress1: '888 Medical Center',
    shippingAddress2: 'Building 2',
    shippingCountry: 'United States',
    shippingState: 'Florida',
    shippingCity: 'Miami',
    billingPostal: '33101',
    shippingPhone: '+1-555-0106',
    shippingDeliveryInstructions: 'Deliver to receiving department'
  },
  {
    name: 'Pacific Manufacturing',
    primaryContactFirstName: 'Robert',
    primaryContactLastName: 'Taylor',
    primaryContactEmail: 'r.taylor@pacificmfg.com',
    primaryContactPhone: '+1-555-0107',
    accountNumber: 'ACC-007',
    website: 'https://pacificmfg.com',
    notes: 'Manufacturing company, bulk orders',
    billingCurrency: 'USD',
    billingAddress1: '999 Industrial Ave',
    billingAddress2: 'Unit 50',
    billingCountry: 'United States',
    billingState: 'Washington',
    billingCity: 'Seattle',
    billingPostal: '98101',
    shippingName: 'Pacific Manufacturing',
    shippingAddress1: '999 Industrial Ave',
    shippingAddress2: 'Unit 50',
    shippingCountry: 'United States',
    shippingState: 'Washington',
    shippingCity: 'Seattle',
    billingPostal: '98101',
    shippingPhone: '+1-555-0107',
    shippingDeliveryInstructions: 'Forklift required'
  },
  {
    name: 'Green Energy Solutions',
    primaryContactFirstName: 'Jennifer',
    primaryContactLastName: 'Martinez',
    primaryContactEmail: 'j.martinez@greenenergy.com',
    primaryContactPhone: '+1-555-0108',
    accountNumber: 'ACC-008',
    website: 'https://greenenergy.com',
    notes: 'Renewable energy company',
    billingCurrency: 'USD',
    billingAddress1: '777 Eco Park',
    billingAddress2: '',
    billingCountry: 'United States',
    billingState: 'Arizona',
    billingCity: 'Phoenix',
    billingPostal: '85001',
    shippingName: 'Green Energy Solutions',
    shippingAddress1: '777 Eco Park',
    shippingAddress2: '',
    shippingCountry: 'United States',
    shippingState: 'Arizona',
    shippingCity: 'Phoenix',
    billingPostal: '85001',
    shippingPhone: '+1-555-0108',
    shippingDeliveryInstructions: 'Eco-friendly packaging preferred'
  },
  {
    name: 'Urban Fashion Co',
    primaryContactFirstName: 'Kevin',
    primaryContactLastName: 'Lee',
    primaryContactEmail: 'kevin.lee@urbanfashion.com',
    primaryContactPhone: '+1-555-0109',
    accountNumber: 'ACC-009',
    website: 'https://urbanfashion.com',
    notes: 'Fashion retailer, seasonal orders',
    billingCurrency: 'USD',
    billingAddress1: '444 Fashion District',
    billingAddress2: 'Suite 200',
    billingCountry: 'United States',
    billingState: 'Illinois',
    billingCity: 'Chicago',
    billingPostal: '60601',
    shippingName: 'Urban Fashion Co',
    shippingAddress1: '444 Fashion District',
    shippingAddress2: 'Suite 200',
    shippingCountry: 'United States',
    billingState: 'Illinois',
    shippingCity: 'Chicago',
    billingPostal: '60601',
    shippingPhone: '+1-555-0109',
    shippingDeliveryInstructions: 'Handle with care'
  },
  {
    name: 'Digital Marketing Pro',
    primaryContactFirstName: 'Amanda',
    primaryContactLastName: 'White',
    primaryContactEmail: 'amanda@digitalmarketingpro.com',
    primaryContactPhone: '+1-555-0110',
    accountNumber: 'ACC-010',
    website: 'https://digitalmarketingpro.com',
    notes: 'Marketing agency, monthly retainers',
    billingCurrency: 'USD',
    billingAddress1: '222 Tech Hub',
    billingAddress2: '',
    billingCountry: 'United States',
    billingState: 'Georgia',
    billingCity: 'Atlanta',
    billingPostal: '30301',
    shippingName: 'Digital Marketing Pro',
    shippingAddress1: '222 Tech Hub',
    shippingAddress2: '',
    shippingCountry: 'United States',
    billingState: 'Georgia',
    shippingCity: 'Atlanta',
    billingPostal: '30301',
    shippingPhone: '+1-555-0110',
    shippingDeliveryInstructions: 'Signature required'
  }
];

const seedCustomers = async () => {
  try {
    // Clear existing customers
    await Customer.deleteMany({});
    console.log('🗑️ Cleared existing customers');

    // Insert one by one to trigger pre-save middleware
    for (const customer of customers) {
      const newCustomer = new Customer(customer);
      await newCustomer.save();
    }
    console.log('✅ 10 customers seeded successfully.');
  } catch (error) {
    console.error('❌ Error seeding customers:', error);
  }
};

module.exports = seedCustomers;
