const mongoose = require('mongoose');
const { InvoiceOrQuote } = require('../models/invoiceQuote');

const invoices = [
  {
    type: 'Invoice',
    orderNumber: 'INV-2024-001',
    note: 'Monthly web development services',
    dateOrdered: new Date('2024-01-15'),
    dateDue: new Date('2024-02-15'),
    orderTotal: 4500.00,
    billingFirstName: 'John',
    billingLastName: 'Smith',
    billingCity: 'San Francisco',
    billingAddress: '123 Business Park, Suite 100',
    billingState: 'California',
    billingEmailAddress: 'john.smith@acme.com',
    shippingFirstName: 'John',
    shippingLastName: 'Smith',
    shippingAddress: '123 Business Park, Suite 100',
    shippingCity: 'San Francisco',
    shippingState: 'California',
    shippingPostcode: '94102',
    shippingMethod: 'Standard Ground',
    paymentMethod: 'Bank Transfer',
    paymentDates: '2024-01-15',
    paymentPaid: 4500.00,
    paymentDue: 0.00,
    paymentTerms: 'Net 30',
    payments: [{
      datePaid: new Date('2024-01-20'),
      outstandingOrderBalance: new Date('2024-01-20'),
      orderPaymentAmount: 4500.00,
      totalPaymentAmount: 4500.00,
      refundedAmount: 0,
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'paid'
    }],
    items: [{
      orderNumber: 'INV-2024-001',
      productName: 'Web Development Services',
      productCode: 'WEB-001',
      size: 'N/A',
      color: 'N/A',
      lineQty: 1,
      decorationProcess: 'N/A',
      unitPrice: 4500.00,
      lineTotal: 4500.00,
      tax: 382.50,
      taxExempt: false,
      orderShippingTotal: 0,
      poNumber: 'PO-ACME-001',
      supplierPoNumber: 'SUP-001',
      productionStaffAccount: 'dev-team',
      storeName: 'Acme Corporation',
      company: 'Acme Corporation',
      billingFirstName: 'John',
      billingLastName: 'Smith',
      billingEmailAddress: 'john.smith@acme.com',
      billingAddress: '123 Business Park, Suite 100',
      billingCity: 'San Francisco',
      billingState: 'California',
      billingPostcode: '94102',
      billingPhoneNo: '+1-555-0101',
      shippingFirstName: 'John',
      shippingLastName: 'Smith',
      shippingAddress: '123 Business Park, Suite 100',
      shippingCity: 'San Francisco',
      shippingState: 'California',
      shippingPostcode: '94102',
      shippingPhoneNo: '+1-555-0101',
      shippingMethod: 'Standard Ground',
      designName: 'N/A',
      designPrice: 0,
      sQty: 0, sPrice: 0, sTotal: 0,
      mQty: 0, mPrice: 0, mTotal: 0,
      lQty: 0, lPrice: 0, lTotal: 0,
      xlQty: 0, xlPrice: 0, xlTotal: 0,
      '2xlQty': 0, '2xlPrice': 0, '2xlTotal': 0,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  },
  {
    type: 'Invoice',
    orderNumber: 'INV-2024-002',
    note: 'Q1 consulting services',
    dateOrdered: new Date('2024-02-01'),
    dateDue: new Date('2024-03-01'),
    orderTotal: 12500.00,
    billingFirstName: 'Sarah',
    billingLastName: 'Johnson',
    billingCity: 'Austin',
    billingAddress: '456 Innovation Drive',
    billingState: 'Texas',
    billingEmailAddress: 'sarah.j@techstart.io',
    shippingFirstName: 'Sarah',
    shippingLastName: 'Johnson',
    shippingAddress: '456 Innovation Drive',
    shippingCity: 'Austin',
    shippingState: 'Texas',
    shippingPostcode: '78701',
    shippingMethod: 'Express',
    paymentMethod: 'Credit Card',
    paymentDates: '2024-02-01',
    paymentPaid: 6250.00,
    paymentDue: 6250.00,
    paymentTerms: 'Net 30',
    payments: [{
      datePaid: new Date('2024-02-15'),
      outstandingOrderBalance: new Date('2024-02-15'),
      orderPaymentAmount: 6250.00,
      totalPaymentAmount: 6250.00,
      refundedAmount: 0,
      paymentMethod: 'Credit Card',
      paymentStatus: 'paid'
    }],
    items: [{
      orderNumber: 'INV-2024-002',
      productName: 'Strategic Consulting',
      productCode: 'CONS-001',
      size: 'N/A',
      color: 'N/A',
      lineQty: 1,
      decorationProcess: 'N/A',
      unitPrice: 12500.00,
      lineTotal: 12500.00,
      tax: 1062.50,
      taxExempt: false,
      orderShippingTotal: 0,
      poNumber: 'PO-TECH-002',
      supplierPoNumber: 'SUP-002',
      productionStaffAccount: 'consulting-team',
      storeName: 'TechStart Solutions',
      company: 'TechStart Solutions',
      billingFirstName: 'Sarah',
      billingLastName: 'Johnson',
      billingEmailAddress: 'sarah.j@techstart.io',
      billingAddress: '456 Innovation Drive',
      billingCity: 'Austin',
      billingState: 'Texas',
      billingPostcode: '78701',
      billingPhoneNo: '+1-555-0102',
      shippingFirstName: 'Sarah',
      shippingLastName: 'Johnson',
      shippingAddress: '456 Innovation Drive',
      shippingCity: 'Austin',
      shippingState: 'Texas',
      shippingPostcode: '78701',
      shippingPhoneNo: '+1-555-0102',
      shippingMethod: 'Express',
      designName: 'N/A',
      designPrice: 0,
      sQty: 0, sPrice: 0, sTotal: 0,
      mQty: 0, mPrice: 0, mTotal: 0,
      lQty: 0, lPrice: 0, lTotal: 0,
      xlQty: 0, xlPrice: 0, xlTotal: 0,
      '2xlQty': 0, '2xlPrice': 0, '2xlTotal': 0,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  },
  {
    type: 'Quote',
    orderNumber: 'QT-2024-003',
    note: 'Bulk merchandise order - pending approval',
    dateOrdered: new Date('2024-03-10'),
    dateDue: new Date('2024-04-10'),
    orderTotal: 28750.00,
    billingFirstName: 'Michael',
    billingLastName: 'Chen',
    billingCity: 'New York',
    billingAddress: '789 Commerce Blvd, Floor 5',
    billingState: 'New York',
    billingEmailAddress: 'm.chen@globalretail.com',
    shippingFirstName: 'Michael',
    shippingLastName: 'Chen',
    shippingAddress: '789 Commerce Blvd, Floor 5',
    shippingCity: 'New York',
    shippingState: 'New York',
    shippingPostcode: '10001',
    shippingMethod: 'Freight',
    paymentMethod: 'Wire Transfer',
    paymentDates: '',
    paymentPaid: 0,
    paymentDue: 28750.00,
    paymentTerms: 'Net 45',
    payments: [],
    items: [{
      orderNumber: 'QT-2024-003',
      productName: 'Custom Branded T-Shirts',
      productCode: 'APP-001',
      size: 'Various',
      color: 'Navy',
      lineQty: 500,
      decorationProcess: 'Screen Print',
      unitPrice: 15.00,
      lineTotal: 7500.00,
      tax: 637.50,
      taxExempt: false,
      orderShippingTotal: 250.00,
      poNumber: 'PO-GLOBAL-003',
      supplierPoNumber: 'SUP-003',
      productionStaffAccount: 'production-team',
      storeName: 'Global Retail Inc',
      company: 'Global Retail Inc',
      billingFirstName: 'Michael',
      billingLastName: 'Chen',
      billingEmailAddress: 'm.chen@globalretail.com',
      billingAddress: '789 Commerce Blvd, Floor 5',
      billingCity: 'New York',
      billingState: 'New York',
      billingPostcode: '10001',
      billingPhoneNo: '+1-555-0103',
      shippingFirstName: 'Michael',
      shippingLastName: 'Chen',
      shippingAddress: '789 Commerce Blvd, Floor 5',
      shippingCity: 'New York',
      shippingState: 'New York',
      shippingPostcode: '10001',
      shippingPhoneNo: '+1-555-0103',
      shippingMethod: 'Freight',
      designName: 'Logo Design v2',
      designPrice: 500.00,
      sQty: 100, sPrice: 15.00, sTotal: 1500.00,
      mQty: 150, mPrice: 15.00, mTotal: 2250.00,
      lQty: 150, lPrice: 15.00, lTotal: 2250.00,
      xlQty: 75, xlPrice: 15.00, xlTotal: 1125.00,
      '2xlQty': 25, '2xlPrice': 15.00, '2xlTotal': 375.00,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  },
  {
    type: 'Invoice',
    orderNumber: 'INV-2024-004',
    note: 'Graphic design project',
    dateOrdered: new Date('2024-03-15'),
    dateDue: new Date('2024-04-15'),
    orderTotal: 3200.00,
    billingFirstName: 'Emma',
    billingLastName: 'Williams',
    billingCity: 'Portland',
    billingAddress: '321 Art District, Studio B',
    billingState: 'Oregon',
    billingEmailAddress: 'emma@creativestudio.co',
    shippingFirstName: 'Emma',
    shippingLastName: 'Williams',
    shippingAddress: '321 Art District, Studio B',
    shippingCity: 'Portland',
    shippingState: 'Oregon',
    shippingPostcode: '97201',
    shippingMethod: 'Digital Delivery',
    paymentMethod: 'PayPal',
    paymentDates: '2024-03-15',
    paymentPaid: 3200.00,
    paymentDue: 0.00,
    paymentTerms: 'Net 15',
    payments: [{
      datePaid: new Date('2024-03-18'),
      outstandingOrderBalance: new Date('2024-03-18'),
      orderPaymentAmount: 3200.00,
      totalPaymentAmount: 3200.00,
      refundedAmount: 0,
      paymentMethod: 'PayPal',
      paymentStatus: 'paid'
    }],
    items: [{
      orderNumber: 'INV-2024-004',
      productName: 'Brand Identity Package',
      productCode: 'DES-001',
      size: 'N/A',
      color: 'N/A',
      lineQty: 1,
      decorationProcess: 'N/A',
      unitPrice: 3200.00,
      lineTotal: 3200.00,
      tax: 272.00,
      taxExempt: false,
      orderShippingTotal: 0,
      poNumber: 'PO-CREATIVE-004',
      supplierPoNumber: 'SUP-004',
      productionStaffAccount: 'design-team',
      storeName: 'Creative Design Studio',
      company: 'Creative Design Studio',
      billingFirstName: 'Emma',
      billingLastName: 'Williams',
      billingEmailAddress: 'emma@creativestudio.co',
      billingAddress: '321 Art District, Studio B',
      billingCity: 'Portland',
      billingState: 'Oregon',
      billingPostcode: '97201',
      billingPhoneNo: '+1-555-0104',
      shippingFirstName: 'Emma',
      shippingLastName: 'Williams',
      shippingAddress: '321 Art District, Studio B',
      shippingCity: 'Portland',
      shippingState: 'Oregon',
      shippingPostcode: '97201',
      shippingPhoneNo: '+1-555-0104',
      shippingMethod: 'Digital Delivery',
      designName: 'N/A',
      designPrice: 0,
      sQty: 0, sPrice: 0, sTotal: 0,
      mQty: 0, mPrice: 0, mTotal: 0,
      lQty: 0, lPrice: 0, lTotal: 0,
      xlQty: 0, xlPrice: 0, xlTotal: 0,
      '2xlQty': 0, '2xlPrice': 0, '2xlTotal': 0,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  },
  {
    type: 'Invoice',
    orderNumber: 'INV-2024-005',
    note: 'Warehouse equipment rental',
    dateOrdered: new Date('2024-04-01'),
    dateDue: new Date('2024-05-01'),
    orderTotal: 8900.00,
    billingFirstName: 'David',
    billingLastName: 'Brown',
    billingCity: 'Denver',
    billingAddress: '555 Warehouse Way',
    billingState: 'Colorado',
    billingEmailAddress: 'd.brown@mountainviewlogistics.com',
    shippingFirstName: 'David',
    shippingLastName: 'Brown',
    shippingAddress: '555 Warehouse Way',
    shippingCity: 'Denver',
    shippingState: 'Colorado',
    shippingPostcode: '80202',
    shippingMethod: 'Local Delivery',
    paymentMethod: 'Check',
    paymentDates: '2024-04-01',
    paymentPaid: 4450.00,
    paymentDue: 4450.00,
    paymentTerms: 'Net 30',
    payments: [{
      datePaid: new Date('2024-04-15'),
      outstandingOrderBalance: new Date('2024-04-15'),
      orderPaymentAmount: 4450.00,
      totalPaymentAmount: 4450.00,
      refundedAmount: 0,
      paymentMethod: 'Check',
      paymentStatus: 'paid'
    }],
    items: [{
      orderNumber: 'INV-2024-005',
      productName: 'Forklift Rental (Monthly)',
      productCode: 'EQP-001',
      size: 'N/A',
      color: 'N/A',
      lineQty: 2,
      decorationProcess: 'N/A',
      unitPrice: 4450.00,
      lineTotal: 8900.00,
      tax: 756.50,
      taxExempt: false,
      orderShippingTotal: 0,
      poNumber: 'PO-LOGISTICS-005',
      supplierPoNumber: 'SUP-005',
      productionStaffAccount: 'equipment-team',
      storeName: 'Mountain View Logistics',
      company: 'Mountain View Logistics',
      billingFirstName: 'David',
      billingLastName: 'Brown',
      billingEmailAddress: 'd.brown@mountainviewlogistics.com',
      billingAddress: '555 Warehouse Way',
      billingCity: 'Denver',
      billingState: 'Colorado',
      billingPostcode: '80202',
      billingPhoneNo: '+1-555-0105',
      shippingFirstName: 'David',
      shippingLastName: 'Brown',
      shippingAddress: '555 Warehouse Way',
      shippingCity: 'Denver',
      shippingState: 'Colorado',
      shippingPostcode: '80202',
      shippingPhoneNo: '+1-555-0105',
      shippingMethod: 'Local Delivery',
      designName: 'N/A',
      designPrice: 0,
      sQty: 0, sPrice: 0, sTotal: 0,
      mQty: 0, mPrice: 0, mTotal: 0,
      lQty: 0, lPrice: 0, lTotal: 0,
      xlQty: 0, xlPrice: 0, xlTotal: 0,
      '2xlQty': 0, '2xlPrice': 0, '2xlTotal': 0,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  },
  {
    type: 'Invoice',
    orderNumber: 'INV-2024-006',
    note: 'Medical supplies order',
    dateOrdered: new Date('2024-04-15'),
    dateDue: new Date('2024-05-15'),
    orderTotal: 15600.00,
    billingFirstName: 'Lisa',
    billingLastName: 'Anderson',
    billingCity: 'Miami',
    billingAddress: '888 Medical Center, Building 2',
    billingState: 'Florida',
    billingEmailAddress: 'lisa.anderson@sunrisehealth.com',
    shippingFirstName: 'Lisa',
    shippingLastName: 'Anderson',
    shippingAddress: '888 Medical Center, Building 2',
    shippingCity: 'Miami',
    shippingState: 'Florida',
    shippingPostcode: '33101',
    shippingMethod: 'Medical Courier',
    paymentMethod: 'Bank Transfer',
    paymentDates: '2024-04-15',
    paymentPaid: 15600.00,
    paymentDue: 0.00,
    paymentTerms: 'Net 30',
    payments: [{
      datePaid: new Date('2024-04-20'),
      outstandingOrderBalance: new Date('2024-04-20'),
      orderPaymentAmount: 15600.00,
      totalPaymentAmount: 15600.00,
      refundedAmount: 0,
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'paid'
    }],
    items: [{
      orderNumber: 'INV-2024-006',
      productName: 'Medical Examination Gloves',
      productCode: 'MED-001',
      size: 'Various',
      color: 'White',
      lineQty: 10000,
      decorationProcess: 'N/A',
      unitPrice: 1.56,
      lineTotal: 15600.00,
      tax: 1326.00,
      taxExempt: false,
      orderShippingTotal: 0,
      poNumber: 'PO-HEALTH-006',
      supplierPoNumber: 'SUP-006',
      productionStaffAccount: 'medical-team',
      storeName: 'Sunrise Healthcare',
      company: 'Sunrise Healthcare',
      billingFirstName: 'Lisa',
      billingLastName: 'Anderson',
      billingEmailAddress: 'lisa.anderson@sunrisehealth.com',
      billingAddress: '888 Medical Center, Building 2',
      billingCity: 'Miami',
      billingState: 'Florida',
      billingPostcode: '33101',
      billingPhoneNo: '+1-555-0106',
      shippingFirstName: 'Lisa',
      shippingLastName: 'Anderson',
      shippingAddress: '888 Medical Center, Building 2',
      shippingCity: 'Miami',
      shippingState: 'Florida',
      shippingPostcode: '33101',
      shippingPhoneNo: '+1-555-0106',
      shippingMethod: 'Medical Courier',
      designName: 'N/A',
      designPrice: 0,
      sQty: 0, sPrice: 0, sTotal: 0,
      mQty: 0, mPrice: 0, mTotal: 0,
      lQty: 0, lPrice: 0, lTotal: 0,
      xlQty: 0, xlPrice: 0, xlTotal: 0,
      '2xlQty': 0, '2xlPrice': 0, '2xlTotal': 0,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  },
  {
    type: 'Quote',
    orderNumber: 'QT-2024-007',
    note: 'Custom manufacturing components',
    dateOrdered: new Date('2024-05-01'),
    dateDue: new Date('2024-06-01'),
    orderTotal: 42500.00,
    billingFirstName: 'Robert',
    billingLastName: 'Taylor',
    billingCity: 'Seattle',
    billingAddress: '999 Industrial Ave, Unit 50',
    billingState: 'Washington',
    billingEmailAddress: 'r.taylor@pacificmfg.com',
    shippingFirstName: 'Robert',
    shippingLastName: 'Taylor',
    shippingAddress: '999 Industrial Ave, Unit 50',
    shippingCity: 'Seattle',
    shippingState: 'Washington',
    shippingPostcode: '98101',
    shippingMethod: 'Freight',
    paymentMethod: 'Wire Transfer',
    paymentDates: '',
    paymentPaid: 0,
    paymentDue: 42500.00,
    paymentTerms: 'Net 45',
    payments: [],
    items: [{
      orderNumber: 'QT-2024-007',
      productName: 'Custom Metal Brackets',
      productCode: 'MFG-001',
      size: 'Custom',
      color: 'Silver',
      lineQty: 1000,
      decorationProcess: 'CNC Machining',
      unitPrice: 42.50,
      lineTotal: 42500.00,
      tax: 3612.50,
      taxExempt: false,
      orderShippingTotal: 500.00,
      poNumber: 'PO-PACIFIC-007',
      supplierPoNumber: 'SUP-007',
      productionStaffAccount: 'manufacturing-team',
      storeName: 'Pacific Manufacturing',
      company: 'Pacific Manufacturing',
      billingFirstName: 'Robert',
      billingLastName: 'Taylor',
      billingEmailAddress: 'r.taylor@pacificmfg.com',
      billingAddress: '999 Industrial Ave, Unit 50',
      billingCity: 'Seattle',
      billingState: 'Washington',
      billingPostcode: '98101',
      billingPhoneNo: '+1-555-0107',
      shippingFirstName: 'Robert',
      shippingLastName: 'Taylor',
      shippingAddress: '999 Industrial Ave, Unit 50',
      shippingCity: 'Seattle',
      shippingState: 'Washington',
      shippingPostcode: '98101',
      shippingPhoneNo: '+1-555-0107',
      shippingMethod: 'Freight',
      designName: 'Bracket Design v3',
      designPrice: 750.00,
      sQty: 0, sPrice: 0, sTotal: 0,
      mQty: 0, mPrice: 0, mTotal: 0,
      lQty: 0, lPrice: 0, lTotal: 0,
      xlQty: 0, xlPrice: 0, xlTotal: 0,
      '2xlQty': 0, '2xlPrice': 0, '2xlTotal': 0,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  },
  {
    type: 'Invoice',
    orderNumber: 'INV-2024-008',
    note: 'Solar panel installation services',
    dateOrdered: new Date('2024-05-10'),
    dateDue: new Date('2024-06-10'),
    orderTotal: 35000.00,
    billingFirstName: 'Jennifer',
    billingLastName: 'Martinez',
    billingCity: 'Phoenix',
    billingAddress: '777 Eco Park',
    billingState: 'Arizona',
    billingEmailAddress: 'j.martinez@greenenergy.com',
    shippingFirstName: 'Jennifer',
    shippingLastName: 'Martinez',
    shippingAddress: '777 Eco Park',
    shippingCity: 'Phoenix',
    shippingState: 'Arizona',
    shippingPostcode: '85001',
    shippingMethod: 'Specialized Transport',
    paymentMethod: 'Bank Transfer',
    paymentDates: '2024-05-10',
    paymentPaid: 17500.00,
    paymentDue: 17500.00,
    paymentTerms: 'Net 30',
    payments: [{
      datePaid: new Date('2024-05-20'),
      outstandingOrderBalance: new Date('2024-05-20'),
      orderPaymentAmount: 17500.00,
      totalPaymentAmount: 17500.00,
      refundedAmount: 0,
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'paid'
    }],
    items: [{
      orderNumber: 'INV-2024-008',
      productName: 'Solar Panel Installation',
      productCode: 'SOL-001',
      size: 'N/A',
      color: 'N/A',
      lineQty: 1,
      decorationProcess: 'N/A',
      unitPrice: 35000.00,
      lineTotal: 35000.00,
      tax: 2975.00,
      taxExempt: false,
      orderShippingTotal: 0,
      poNumber: 'PO-GREEN-008',
      supplierPoNumber: 'SUP-008',
      productionStaffAccount: 'solar-team',
      storeName: 'Green Energy Solutions',
      company: 'Green Energy Solutions',
      billingFirstName: 'Jennifer',
      billingLastName: 'Martinez',
      billingEmailAddress: 'j.martinez@greenenergy.com',
      billingAddress: '777 Eco Park',
      billingCity: 'Phoenix',
      billingState: 'Arizona',
      billingPostcode: '85001',
      billingPhoneNo: '+1-555-0108',
      shippingFirstName: 'Jennifer',
      shippingLastName: 'Martinez',
      shippingAddress: '777 Eco Park',
      shippingCity: 'Phoenix',
      shippingState: 'Arizona',
      shippingPostcode: '85001',
      shippingPhoneNo: '+1-555-0108',
      shippingMethod: 'Specialized Transport',
      designName: 'N/A',
      designPrice: 0,
      sQty: 0, sPrice: 0, sTotal: 0,
      mQty: 0, mPrice: 0, mTotal: 0,
      lQty: 0, lPrice: 0, lTotal: 0,
      xlQty: 0, xlPrice: 0, xlTotal: 0,
      '2xlQty': 0, '2xlPrice': 0, '2xlTotal': 0,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  },
  {
    type: 'Invoice',
    orderNumber: 'INV-2024-009',
    note: 'Seasonal fashion collection',
    dateOrdered: new Date('2024-05-15'),
    dateDue: new Date('2024-06-15'),
    orderTotal: 18900.00,
    billingFirstName: 'Kevin',
    billingLastName: 'Lee',
    billingCity: 'Chicago',
    billingAddress: '444 Fashion District, Suite 200',
    billingState: 'Illinois',
    billingEmailAddress: 'kevin.lee@urbanfashion.com',
    shippingFirstName: 'Kevin',
    shippingLastName: 'Lee',
    shippingAddress: '444 Fashion District, Suite 200',
    shippingCity: 'Chicago',
    shippingState: 'Illinois',
    shippingPostcode: '60601',
    shippingMethod: 'Ground',
    paymentMethod: 'Credit Card',
    paymentDates: '2024-05-15',
    paymentPaid: 18900.00,
    paymentDue: 0.00,
    paymentTerms: 'Net 30',
    payments: [{
      datePaid: new Date('2024-05-18'),
      outstandingOrderBalance: new Date('2024-05-18'),
      orderPaymentAmount: 18900.00,
      totalPaymentAmount: 18900.00,
      refundedAmount: 0,
      paymentMethod: 'Credit Card',
      paymentStatus: 'paid'
    }],
    items: [{
      orderNumber: 'INV-2024-009',
      productName: 'Designer Jackets',
      productCode: 'FASH-001',
      size: 'Various',
      color: 'Black',
      lineQty: 150,
      decorationProcess: 'Embroidery',
      unitPrice: 126.00,
      lineTotal: 18900.00,
      tax: 1606.50,
      taxExempt: false,
      orderShippingTotal: 0,
      poNumber: 'PO-URBAN-009',
      supplierPoNumber: 'SUP-009',
      productionStaffAccount: 'fashion-team',
      storeName: 'Urban Fashion Co',
      company: 'Urban Fashion Co',
      billingFirstName: 'Kevin',
      billingLastName: 'Lee',
      billingEmailAddress: 'kevin.lee@urbanfashion.com',
      billingAddress: '444 Fashion District, Suite 200',
      billingCity: 'Chicago',
      billingState: 'Illinois',
      billingPostcode: '60601',
      billingPhoneNo: '+1-555-0109',
      shippingFirstName: 'Kevin',
      shippingLastName: 'Lee',
      shippingAddress: '444 Fashion District, Suite 200',
      shippingCity: 'Chicago',
      shippingState: 'Illinois',
      shippingPostcode: '60601',
      shippingPhoneNo: '+1-555-0109',
      shippingMethod: 'Ground',
      designName: 'Logo Embroidery',
      designPrice: 450.00,
      sQty: 30, sPrice: 126.00, sTotal: 3780.00,
      mQty: 45, mPrice: 126.00, mTotal: 5670.00,
      lQty: 45, lPrice: 126.00, mTotal: 5670.00,
      xlQty: 20, xlPrice: 126.00, xlTotal: 2520.00,
      '2xlQty': 10, '2xlPrice': 126.00, '2xlTotal': 1260.00,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  },
  {
    type: 'Invoice',
    orderNumber: 'INV-2024-010',
    note: 'Monthly marketing retainer',
    dateOrdered: new Date('2024-05-20'),
    dateDue: new Date('2024-06-20'),
    orderTotal: 7500.00,
    billingFirstName: 'Amanda',
    billingLastName: 'White',
    billingCity: 'Atlanta',
    billingAddress: '222 Tech Hub',
    billingState: 'Georgia',
    billingEmailAddress: 'amanda@digitalmarketingpro.com',
    shippingFirstName: 'Amanda',
    shippingLastName: 'White',
    shippingAddress: '222 Tech Hub',
    shippingCity: 'Atlanta',
    shippingState: 'Georgia',
    shippingPostcode: '30301',
    shippingMethod: 'Digital Delivery',
    paymentMethod: 'Bank Transfer',
    paymentDates: '2024-05-20',
    paymentPaid: 7500.00,
    paymentDue: 0.00,
    paymentTerms: 'Net 30',
    payments: [{
      datePaid: new Date('2024-05-25'),
      outstandingOrderBalance: new Date('2024-05-25'),
      orderPaymentAmount: 7500.00,
      totalPaymentAmount: 7500.00,
      refundedAmount: 0,
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'paid'
    }],
    items: [{
      orderNumber: 'INV-2024-010',
      productName: 'Digital Marketing Services',
      productCode: 'MKT-001',
      size: 'N/A',
      color: 'N/A',
      lineQty: 1,
      decorationProcess: 'N/A',
      unitPrice: 7500.00,
      lineTotal: 7500.00,
      tax: 637.50,
      taxExempt: false,
      orderShippingTotal: 0,
      poNumber: 'PO-DIGITAL-010',
      supplierPoNumber: 'SUP-010',
      productionStaffAccount: 'marketing-team',
      storeName: 'Digital Marketing Pro',
      company: 'Digital Marketing Pro',
      billingFirstName: 'Amanda',
      billingLastName: 'White',
      billingEmailAddress: 'amanda@digitalmarketingpro.com',
      billingAddress: '222 Tech Hub',
      billingCity: 'Atlanta',
      billingState: 'Georgia',
      billingPostcode: '30301',
      billingPhoneNo: '+1-555-0110',
      shippingFirstName: 'Amanda',
      shippingLastName: 'White',
      shippingAddress: '222 Tech Hub',
      shippingCity: 'Atlanta',
      shippingState: 'Georgia',
      shippingPostcode: '30301',
      shippingPhoneNo: '+1-555-0110',
      shippingMethod: 'Digital Delivery',
      designName: 'N/A',
      designPrice: 0,
      sQty: 0, sPrice: 0, sTotal: 0,
      mQty: 0, mPrice: 0, mTotal: 0,
      lQty: 0, lPrice: 0, lTotal: 0,
      xlQty: 0, xlPrice: 0, xlTotal: 0,
      '2xlQty': 0, '2xlPrice': 0, '2xlTotal': 0,
      '3xlQty': 0, '3xlPrice': 0, '3xlTotal': 0,
      '4xlQty': 0, '4xlPrice': 0, '4xlTotal': 0,
      '5xlQty': 0, '5xlPrice': 0, '5xlTotal': 0
    }]
  }
];

const seedInvoices = async () => {
  try {
    // Clear existing invoices/quotes
    await InvoiceOrQuote.deleteMany({});
    console.log('🗑️ Cleared existing invoices/quotes');

    // Insert one by one to trigger pre-save middleware
    for (const invoice of invoices) {
      const newInvoice = new InvoiceOrQuote(invoice);
      await newInvoice.save();
    }
    console.log('✅ 10 invoices/quotes seeded successfully.');
  } catch (error) {
    console.error('❌ Error seeding invoices:', error);
  }
};

module.exports = seedInvoices;
